name: Deploy Angular to GitHub Pages

on:
  push:
    branches: ["DEV", "RELEASE"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          # Tells cache to look for the lock file in the subfolder
          cache-dependency-path: rajsde-portfolio/package-lock.json

      - name: Install Dependencies
        working-directory: ./rajsde-portfolio    # <--- CRITICAL: Runs inside your project folder
        run: npm ci

      - name: Build
        working-directory: ./rajsde-portfolio    # <--- CRITICAL: Runs build inside your project folder
        run: npm run build -- --configuration production --base-href /

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Path from Root -> Subfolder -> Dist -> Project -> Browser
          folder: rajsde-portfolio/dist/rajsde-portfolio/browser 
          branch: gh-pages